version: "3.7"

volumes:
  postgresql_data:
    driver: local

services:
  postgresql:
    container_name: postgresql-dotlib
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql

  keycloak:
    container_name: keycloak-dotlib
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - postgresql

  mysql:
    container_name: mysql-dotlib
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app1_database
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  myapp1:
    container_name: myapp1-dotlib
    tty: true
    image: docker.io/bitnami/laravel:8-debian-10
    environment:
      - DB_HOST=mysql-dotlib
      - DB_DATABASE=app1_database
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./app1:/app
