version: "3.7"

networks:
  tech-day-network:
    external: true

services:
  keycloak:
    container_name: tech-day-keycloak
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - tech-day-network

  database:
    container_name: tech-day-database
    image: mysql:5.7
    volumes:
      - $HOME/docker-databases/docker-database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - tech-day-network

  app:
    container_name: tech-day-php
    image: docker-php
    build:
      args:
        user: dotlib
        uid: 1000
      context: ./
      dockerfile: docker/app/app.dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app-php:/var/www
    depends_on:
      - nginx
    networks:
      - tech-day-network

  nginx:
    image: nginx:alpine
    container_name: tech-day-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app-php:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - database
    networks:
      - tech-day-network
